//! Long-form workspace CLI help text constants.

pub(crate) const SYNC_ROOT_HELP_TEXT: &str = "Examples:\n\n  Scan one repo root that carries source provenance for Git Sync dashboards, access bundles, alerts/raw, and datasources/provisioning:\n    grafana-util workspace scan ./grafana-oac-repo --output-format table\n\n  Example mixed workspace tree:\n    ./grafana-oac-repo/\n      dashboards/git-sync/raw/\n      dashboards/git-sync/provisioning/\n      access-users/\n      access-teams/\n      access-orgs/\n      access-service-accounts/\n      alerts/raw/\n      datasources/provisioning/datasources.yaml\n\n  Test whether the staged package looks safe to continue:\n    grafana-util workspace test ./grafana-oac-repo --output-format json\n\n  Preview what would change against live Grafana:\n    grafana-util workspace preview ./grafana-oac-repo --fetch-live --profile prod --output-format json\n\n  Package the same mixed workspace into one handoff file:\n    grafana-util workspace package ./grafana-oac-repo --output-file ./workspace-package.json\n\n  Apply a reviewed workspace back to Grafana:\n    grafana-util workspace apply --approve --execute-live --profile prod\n\nCI workflows:\n\n  Test a workspace package against target inventory before apply:\n    grafana-util workspace ci package-test --source-bundle ./workspace-package.json --target-inventory ./target-inventory.json --output-format json\n\n  Test a staged promotion handoff:\n    grafana-util workspace ci promote-test --source-bundle ./workspace-package.json --target-inventory ./target-inventory.json --mapping-file ./promotion-map.json --output-format json";
pub(crate) const SYNC_SCAN_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace scan ./grafana-oac-repo --output-format table\n  grafana-util workspace scan ./grafana-oac-repo --dashboard-export-dir ./dashboards/raw --alert-export-dir ./alerts/raw --output-format json\n\n  Mixed workspace tree:\n    ./grafana-oac-repo/\n      dashboards/git-sync/raw/\n      dashboards/git-sync/provisioning/\n      access-users/\n      access-teams/\n      access-orgs/\n      access-service-accounts/\n      alerts/raw/\n      datasources/provisioning/datasources.yaml";
pub(crate) const SYNC_TEST_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace test ./grafana-oac-repo --output-format json\n  grafana-util workspace test ./grafana-oac-repo --dashboard-provisioning-dir ./dashboards/provisioning --output-format table\n\n  Same mixed workspace root can carry dashboard, access, alert, and datasource provenance together.";
pub(crate) const SYNC_PREVIEW_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace preview ./grafana-oac-repo --fetch-live --profile prod --output-format json\n  grafana-util workspace preview ./grafana-oac-repo --desired-file ./desired.json --live-file ./live.json\n  grafana-util workspace preview ./grafana-oac-repo --dashboard-export-dir ./dashboards/raw --alert-export-dir ./alerts/raw --fetch-live --profile prod --output-file ./workspace-preview.json\n\n  Preview the same mixed workspace root when dashboards, alerts, and datasources live under one repo tree.";
pub(crate) const SYNC_SUMMARY_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci summary --desired-file ./desired.json\n  grafana-util workspace ci summary --desired-file ./desired.json --output-format json";
pub(crate) const SYNC_PLAN_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci plan --desired-file ./desired.json --live-file ./live.json\n  grafana-util workspace ci plan --desired-file ./desired.json --fetch-live --url http://localhost:3000 --token \"$GRAFANA_API_TOKEN\" --allow-prune --output-format json";
pub(crate) const SYNC_REVIEW_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci mark-reviewed --plan-file ./workspace-plan.json\n  grafana-util workspace ci mark-reviewed --plan-file ./workspace-plan.json --review-note 'peer-reviewed' --output-format json";
pub(crate) const SYNC_APPLY_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace apply --preview-file ./workspace-preview.json --approve\n  grafana-util workspace apply --preview-file ./workspace-preview.json --approve --execute-live --allow-folder-delete --profile prod\n  grafana-util workspace apply --preview-file ./workspace-preview.json --approve --execute-live --allow-policy-reset --profile prod";
pub(crate) const SYNC_AUDIT_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci audit --managed-file ./desired.json --live-file ./live.json --write-lock ./workspace-lock.json\n  grafana-util workspace ci audit --lock-file ./workspace-lock.json --fetch-live --url http://localhost:3000 --token \"$GRAFANA_API_TOKEN\" --fail-on-drift --output-format json";
pub(crate) const SYNC_PREFLIGHT_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci input-test --desired-file ./desired.json --availability-file ./availability.json\n  grafana-util workspace ci input-test --desired-file ./desired.json --fetch-live --url http://localhost:3000 --token \"$GRAFANA_API_TOKEN\" --output-format json";
pub(crate) const SYNC_ASSESS_ALERTS_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci alert-readiness --alerts-file ./alerts.json\n  grafana-util workspace ci alert-readiness --alerts-file ./alerts.json --output-format json";
pub(crate) const SYNC_BUNDLE_PREFLIGHT_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci package-test --source-bundle ./workspace-package.json --target-inventory ./target.json\n  grafana-util workspace ci package-test --source-bundle ./workspace-package.json --target-inventory ./target.json --availability-file ./availability.json --output-format json\n\n  Example availability file:\n    {\n      \"providerNames\": [\"vault\"],\n      \"secretPlaceholderNames\": [\"prom-basic-auth\"]\n    }";
pub(crate) const SYNC_PROMOTION_PREFLIGHT_HELP_TEXT: &str = "This command is a staged review handoff for promotion; it stays read-only and does not apply live changes.\n\nExamples:\n\n  grafana-util workspace ci promote-test --source-bundle ./workspace-package.json --target-inventory ./target.json\n  grafana-util workspace ci promote-test --source-bundle ./workspace-package.json --target-inventory ./target.json --mapping-file ./promotion-mapping.json --availability-file ./availability.json --output-format json\n\n  Minimal promotion mapping file:\n    {\n      \"kind\": \"grafana-utils-sync-promotion-mapping\",\n      \"schemaVersion\": 1,\n      \"metadata\": {\n        \"sourceEnvironment\": \"staging\",\n        \"targetEnvironment\": \"prod\"\n      },\n      \"folders\": {\n        \"ops-src\": \"ops-prod\"\n      },\n      \"datasources\": {\n        \"uids\": {\n          \"prom-src\": \"prom-prod\"\n        },\n        \"names\": {\n          \"Prometheus Source\": \"Prometheus Prod\"\n        }\n      }\n    }\n\n  Example availability file:\n    {\n      \"providerNames\": [\"vault\"],\n      \"secretPlaceholderNames\": [\"prom-basic-auth\"]\n    }";
pub(crate) const SYNC_PACKAGE_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace package ./grafana-oac-repo --dashboard-export-dir ./dashboards/raw --alert-export-dir ./alerts/raw --output-file ./workspace-package.json\n  grafana-util workspace package ./grafana-oac-repo --dashboard-export-dir ./dashboards/raw --datasource-export-file ./datasources/datasources.json --output-format json\n  grafana-util workspace package ./grafana-oac-repo --dashboard-export-dir ./dashboards/raw --datasource-provisioning-file ./datasources/provisioning/datasources.yaml --output-format json\n  grafana-util workspace package ./grafana-oac-repo --dashboard-provisioning-dir ./dashboards/provisioning --alert-export-dir ./alerts/raw --output-file ./workspace-package.json\n  grafana-util workspace package ./grafana-oac-repo --output-file ./workspace-package.json\n\n  Mixed workspace package handoff:\n    use one repo root that carries dashboards/git-sync/raw, dashboards/git-sync/provisioning,\n    alerts/raw, and datasources/provisioning/datasources.yaml, then package the surfaced\n    dashboards, alerts, and datasource provenance into ./workspace-package.json.";
pub(crate) const SYNC_CI_HELP_TEXT: &str = "Examples:\n\n  grafana-util workspace ci summary --desired-file ./desired.json\n  grafana-util workspace ci mark-reviewed --plan-file ./workspace-plan.json --review-note 'peer-reviewed'\n  grafana-util workspace ci package-test --source-bundle ./workspace-package.json --target-inventory ./target.json --output-format json";
