//! Catalog lookup/modeling logic for Core data sources and metadata.

use clap::ValueEnum;
use serde_json::Value;

/// One supported datasource type entry grouped under a higher-level category.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DatasourceCatalogEntry {
    pub category: &'static str,
    pub type_id: &'static str,
    pub display_name: &'static str,
    pub aliases: &'static [&'static str],
    pub profile: &'static str,
    pub query_language: &'static str,
    pub suggested_flags: &'static [&'static str],
    pub target: &'static str,
    pub requires_url: bool,
    pub url_example: &'static str,
    pub add_defaults_access: Option<&'static str>,
    pub add_defaults_http_method: Option<&'static str>,
    pub add_defaults_time_field: Option<&'static str>,
    pub add_defaults_json_data: &'static [(&'static str, DatasourceCatalogJsonDefaultValue)],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum DatasourcePresetProfile {
    Starter,
    Full,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DatasourceCatalogJsonDefaultValue {
    Bool(bool),
    Number(i64),
    String(&'static str),
}

impl DatasourceCatalogJsonDefaultValue {
    pub(crate) fn to_json_value(self) -> Value {
        match self {
            Self::Bool(value) => Value::Bool(value),
            Self::Number(value) => Value::Number(value.into()),
            Self::String(value) => Value::String(value.to_string()),
        }
    }

    pub(crate) fn to_display_value(self) -> String {
        match self {
            Self::Bool(value) => value.to_string(),
            Self::Number(value) => value.to_string(),
            Self::String(value) => value.to_string(),
        }
    }
}

pub(crate) const DATASOURCE_CATALOG: &[DatasourceCatalogEntry] = &[
    DatasourceCatalogEntry {
        category: "Metrics",
        type_id: "prometheus",
        display_name: "Prometheus",
        aliases: &["grafana-prometheus-datasource"],
        profile: "metrics-http",
        query_language: "promql",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--with-credentials",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://prometheus:9090",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: Some("POST"),
        add_defaults_time_field: None,
        add_defaults_json_data: &[],
    },
    DatasourceCatalogEntry {
        category: "Metrics",
        type_id: "influxdb",
        display_name: "InfluxDB",
        aliases: &["grafana-influxdb-datasource", "flux"],
        profile: "metrics-http",
        query_language: "flux-or-influxql",
        suggested_flags: &[
            "--user",
            "--password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://influxdb:8086",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            ("version", DatasourceCatalogJsonDefaultValue::String("Flux")),
            (
                "organization",
                DatasourceCatalogJsonDefaultValue::String("main-org"),
            ),
            (
                "defaultBucket",
                DatasourceCatalogJsonDefaultValue::String("metrics"),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Metrics",
        type_id: "graphite",
        display_name: "Graphite",
        aliases: &[],
        profile: "metrics-http",
        query_language: "graphite",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://graphite:8080",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[(
            "graphiteVersion",
            DatasourceCatalogJsonDefaultValue::String("1.1"),
        )],
    },
    DatasourceCatalogEntry {
        category: "Metrics",
        type_id: "opentsdb",
        display_name: "OpenTSDB",
        aliases: &[],
        profile: "metrics-http",
        query_language: "opentsdb",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://opentsdb:4242",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[("tsdbVersion", DatasourceCatalogJsonDefaultValue::Number(2))],
    },
    DatasourceCatalogEntry {
        category: "Logs",
        type_id: "loki",
        display_name: "Loki",
        aliases: &["grafana-loki-datasource"],
        profile: "logs-http",
        query_language: "logql",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://loki:3100",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            ("maxLines", DatasourceCatalogJsonDefaultValue::Number(1000)),
            ("timeout", DatasourceCatalogJsonDefaultValue::Number(60)),
        ],
    },
    DatasourceCatalogEntry {
        category: "Logs",
        type_id: "elasticsearch",
        display_name: "Elasticsearch",
        aliases: &[],
        profile: "logs-search-api",
        query_language: "lucene-or-query-dsl",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--user",
            "--password",
            "--with-credentials",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://elasticsearch:9200",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: Some("@timestamp"),
        add_defaults_json_data: &[],
    },
    DatasourceCatalogEntry {
        category: "Logs",
        type_id: "opensearch",
        display_name: "OpenSearch",
        aliases: &[],
        profile: "logs-search-api",
        query_language: "ppl-or-query-dsl",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--user",
            "--password",
            "--with-credentials",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://opensearch:9200",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: Some("@timestamp"),
        add_defaults_json_data: &[],
    },
    DatasourceCatalogEntry {
        category: "Tracing",
        type_id: "jaeger",
        display_name: "Jaeger",
        aliases: &[],
        profile: "tracing-http",
        query_language: "trace-search",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://jaeger:16686",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "nodeGraph.enabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "traceQuery.timeShiftEnabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Tracing",
        type_id: "zipkin",
        display_name: "Zipkin",
        aliases: &[],
        profile: "tracing-http",
        query_language: "trace-search",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://zipkin:9411",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "nodeGraph.enabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "traceQuery.timeShiftEnabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Tracing",
        type_id: "tempo",
        display_name: "Tempo",
        aliases: &[],
        profile: "tracing-http",
        query_language: "traceql",
        suggested_flags: &[
            "--basic-auth",
            "--basic-auth-user",
            "--basic-auth-password",
            "--http-header",
            "--tls-skip-verify",
            "--server-name",
        ],
        target: "http-api",
        requires_url: true,
        url_example: "http://tempo:3200",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "nodeGraph.enabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "search.hide",
                DatasourceCatalogJsonDefaultValue::Bool(false),
            ),
            (
                "traceQuery.timeShiftEnabled",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "traceQuery.spanStartTimeShift",
                DatasourceCatalogJsonDefaultValue::String("-1h"),
            ),
            (
                "traceQuery.spanEndTimeShift",
                DatasourceCatalogJsonDefaultValue::String("1h"),
            ),
            (
                "streamingEnabled.search",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Databases",
        type_id: "mysql",
        display_name: "MySQL",
        aliases: &["grafana-mysql-datasource"],
        profile: "sql-database",
        query_language: "sql",
        suggested_flags: &["--user", "--password", "--tls-skip-verify", "--server-name"],
        target: "sql-database",
        requires_url: true,
        url_example: "mysql://mysql:3306",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "database",
                DatasourceCatalogJsonDefaultValue::String("grafana"),
            ),
            (
                "maxOpenConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConnsAuto",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "connMaxLifetime",
                DatasourceCatalogJsonDefaultValue::Number(14400),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Databases",
        type_id: "postgresql",
        display_name: "PostgreSQL",
        aliases: &["postgres", "grafana-postgresql-datasource"],
        profile: "sql-database",
        query_language: "sql",
        suggested_flags: &["--user", "--password", "--tls-skip-verify", "--server-name"],
        target: "sql-database",
        requires_url: true,
        url_example: "postgres://postgres:5432",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "database",
                DatasourceCatalogJsonDefaultValue::String("grafana"),
            ),
            (
                "sslmode",
                DatasourceCatalogJsonDefaultValue::String("disable"),
            ),
            (
                "maxOpenConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConnsAuto",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "connMaxLifetime",
                DatasourceCatalogJsonDefaultValue::Number(14400),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Databases",
        type_id: "mssql",
        display_name: "MSSQL",
        aliases: &[],
        profile: "sql-database",
        query_language: "sql",
        suggested_flags: &["--user", "--password", "--tls-skip-verify", "--server-name"],
        target: "sql-database",
        requires_url: true,
        url_example: "sqlserver://sqlserver:1433",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[
            (
                "database",
                DatasourceCatalogJsonDefaultValue::String("grafana"),
            ),
            (
                "maxOpenConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConns",
                DatasourceCatalogJsonDefaultValue::Number(100),
            ),
            (
                "maxIdleConnsAuto",
                DatasourceCatalogJsonDefaultValue::Bool(true),
            ),
            (
                "connMaxLifetime",
                DatasourceCatalogJsonDefaultValue::Number(14400),
            ),
            (
                "connectionTimeout",
                DatasourceCatalogJsonDefaultValue::Number(0),
            ),
        ],
    },
    DatasourceCatalogEntry {
        category: "Databases",
        type_id: "sqlite",
        display_name: "SQLite",
        aliases: &[],
        profile: "sql-database",
        query_language: "sql",
        suggested_flags: &["--user", "--password"],
        target: "embedded-database",
        requires_url: false,
        url_example: "file:/var/lib/sqlite/grafana.db",
        add_defaults_access: Some("proxy"),
        add_defaults_http_method: None,
        add_defaults_time_field: None,
        add_defaults_json_data: &[(
            "path",
            DatasourceCatalogJsonDefaultValue::String("/var/lib/sqlite/grafana.db"),
        )],
    },
];
