from __future__ import annotations

import html
from pathlib import Path

from docgen_common import relative_href
from docsite_html_common import html_list, prefixed_output_rel, render_template, render_version_links
from docsite_html_nav import render_global_nav, render_jump_select
from docsite_html_page_shell import page_shell
from docsite_html_roff import render_roff_manpage_html
from generate_manpages import NAMESPACE_SPECS


def command_reference_root_for_stem(stem, config):
    if stem == "grafana-util":
        return prefixed_output_rel(config, "commands/en/index.html")
    for spec in NAMESPACE_SPECS:
        if spec.stem == stem:
            return prefixed_output_rel(config, f"commands/en/{spec.root_doc[:-3]}.html")
    return None


def render_manpage_index_page(output_rel, names, config):
    body = (
        "<p>This lane mirrors the checked-in generated manpages as browser-readable HTML for local browsing and GitHub Pages.</p>"
        + "<ul>"
        + "".join(f'<li><a href="{html.escape(relative_href(output_rel, prefixed_output_rel(config, f"man/{Path(name).stem}.html")))}">{html.escape(name)}</a></li>' for name in names)
        + "</ul>"
    )
    related = [
        ("English handbook", relative_href(output_rel, prefixed_output_rel(config, "handbook/en/index.html"))),
        ("English command reference", relative_href(output_rel, prefixed_output_rel(config, "commands/en/index.html"))),
    ]
    if config.raw_manpage_target_rel:
        related.append(("Top-level roff manpage", relative_href(output_rel, config.raw_manpage_target_rel)))
    return page_shell(
        page_title="Manpages",
        html_lang="en",
        home_href=relative_href(output_rel, prefixed_output_rel(config, "index.html")),
        hero_title="Generated Manpages",
        hero_summary="Browser-readable HTML mirrors of the generated roff pages.",
        breadcrumbs=[("Home", relative_href(output_rel, prefixed_output_rel(config, "index.html"))), ("Manpages", None)],
        body_html=body,
        toc_html="<p>Open a generated manpage mirror or jump back to the command-reference lane.</p>",
        related_html=html_list(related),
        version_html=render_version_links(output_rel, config),
        locale_html="<p>English only. This lane currently generates from English command docs.</p>",
        footer_nav_html="",
        footer_html='Generated from <code>docs/man/*.1</code> via <code>scripts/generate_manpages.py</code>.',
        jump_html=render_jump_select(output_rel, "en", config),
        nav_html=render_global_nav(output_rel, "en", config),
    )


def render_manpage_page(output_rel, name, roff, config):
    stem = Path(name).stem
    command_root = command_reference_root_for_stem(stem, config)
    related = [("Manpage index", relative_href(output_rel, prefixed_output_rel(config, "man/index.html")))]
    if config.raw_manpage_target_rel:
        related.append(("Raw roff source", relative_href(output_rel, prefixed_output_rel(config, f"man/{name}"))))
    if command_root:
        related.append(("Matching command reference", relative_href(output_rel, command_root)))
    body = render_template("manpage_intro.html.tmpl", summary_html="This page renders the generated roff manpage into readable HTML for browser use. For richer per-subcommand detail, prefer the command-reference pages.", body_html=render_roff_manpage_html(roff))
    return page_shell(
        page_title=name,
        html_lang="en",
        home_href=relative_href(output_rel, prefixed_output_rel(config, "index.html")),
        hero_title=name,
        hero_summary="Browser-readable rendering of a generated roff manpage.",
        breadcrumbs=[("Home", relative_href(output_rel, prefixed_output_rel(config, "index.html"))), ("Manpages", relative_href(output_rel, prefixed_output_rel(config, "man/index.html"))), (name, None)],
        body_html=body,
        toc_html="<p>This page renders the generated manpage into readable HTML sections.</p>",
        related_html=html_list(related),
        version_html=render_version_links(output_rel, config),
        locale_html="<p>English only. The manpage lane currently generates from English command docs.</p>",
        footer_nav_html="",
        footer_html=f'Source: <code>docs/man/{html.escape(name)}</code><br>Generated by <code>scripts/generate_command_html.py</code>.',
        jump_html=render_jump_select(output_rel, "en", config),
        nav_html=render_global_nav(output_rel, "en", config),
    )
